version: '3.5'

services:
  mongodb:
    container_name: mongodb_container
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin}
    volumes:
       - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongodb
    restart: unless-stopped
  
  mongo-express:
    container_name: mongo_express_container
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD:-admin}
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    # volumes:
    #    - pgadmin:/var/lib/pgadmin

    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    networks:
      - mongodb
    restart: unless-stopped

networks:
  mongodb:
    driver: bridge

volumes:
    mongodb:
    # pgadmin: